platform :ios, '8.0'
target ‘Fibonacci’ do
pod ‘AFNetworking’, ‘~> 3.0’
pod 'GTMBase64', '~> 1.0.0'
pod 'FMDB', '~> 2.6.2'
pod 'SVProgressHUD', '2.2.1'
pod 'SDWebImage', '~> 3.7.5'
pod 'Reachability', '~> 3.2'
pod 'Masonry', '~> 1.1.0'
pod 'MJExtension', '~> 3.0.10'
pod 'CocoaLumberjack', '~> 2.2.0'
pod 'BlocksKit', '~> 2.2.5'
pod 'SFHFKeychainUtils', '~> 0.0.1'
pod 'IQKeyboardManager', '~> 4.0.13'
pod 'MZTimerLabel','0.5.4'
# ShareSDK主模块(必须)
pod 'ShareSDK3', '~> 4.0.2'
# Mob 公共库(必须) 如果同时集成SMSSDK iOS2.0:可看此注意事项：http://bbs.mob.com/thread-20051-1-1.html
 pod 'MOBFoundation', '~> 3.0.2'
# UI模块(非必须，需要用到ShareSDK提供的分享菜单栏和分享编辑页面需要以下1行)
pod 'ShareSDK3/ShareSDKUI'
# 平台SDK模块(对照一下平台，需要的加上。如果只需要QQ、微信、新浪微博，只需要以下3行)
pod 'ShareSDK3/ShareSDKPlatforms/QQ'
pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
pod 'ShareSDK3/ShareSDKPlatforms/WeChat'
pre_install do
    system("sed -i '' '/UITextField/d' Pods/BlocksKit/BlocksKit/BlocksKit+UIKit.h")
    system('rm Pods/BlocksKit/BlocksKit/UIKit/UITextField+BlocksKit.h')
    system('rm Pods/BlocksKit/BlocksKit/UIKit/UITextField+BlocksKit.m')
end
end
